var React;
React.useState;
React.memo;
React.createRef;
React.useReducer;
React.useCallback;
React.Fragment;
React.useRef;
React.Element;
React.cloneElement;
React.Component;
React.Component.call;
React.useMemo;
React.useEffect;
React.createElement;
React.createElement.apply;
React.createContext;
var ReactDOM;
ReactDOM.render;
ReactDOM.unmountComponentAtNode;
ReactDOM.hydrate;
ReactDOM.createPortal;
ReactDOM.findDOMNode;
Object.forceUpdate;
Object.current;
Object.renderToString;
Object.renderToStaticMarkup;
Object.out;
Object.out.println;
Object.error;
Object.error.println;
var ReactDOMServer;
ReactDOMServer.renderToString;
ReactDOMServer.renderToStaticMarkup;
var require;
var setTimeout;
var process;
process.hrtime;
var Java;
Java.type;
